#!/bin/bash
#SBATCH --mem=16G
#SBATCH -c 16
#SBATCH -p ei-medium
#SBATCH -J detFrk
#SBATCH --mail-type=END,FAIL
#SBATCH --time=15:59:59

set -e

# check that input file was provided
if [ ! -f "${dnascentDetectFile:-}" ]; then
  >&2 echo "ERROR: input file not found"
  exit 1
fi

# check that script directory was provided
if [ ! -d "${scriptDir:-}" ]; then
  >&2 echo "ERROR: script directory not found"
  exit 1
fi

# shellcheck disable=SC2154
# load DNAscent
source "$scriptDir"/load_package.sh -dnascent

# Clean up step to remove any line from a detect file with negative coordinates.
# This is a workaround for a bug in DNAscent forksense v2.
# In a .detect file generated by DNAscent detect v2, the coordinates in a reversed read
# close to the start of a contig could be negative as the program uses a shifted coordinate system
# for reversed reads (i.e. coordinate of reversed read = real coordinate - some number of bases;
# this shift distance is equal to 5 but the value itself is not relevant for this discussion).
# Forksense reports erroneous coordinates for these negative coordinates.
# So, we have to remove these lines from the .detect file before running forksense.

# set a temporary output file
random_str=$(openssl rand -hex 8)
temp_detect_file="$dnascentDetectFile"."$random_str"

# remove any line with negative coordinates
grep -v "^-" "$dnascentDetectFile" > "$temp_detect_file"

numThreads=16

# shellcheck disable=SC2154
DNAscent forkSense -d "$temp_detect_file" -o "$dnascentForkSenseFile" -t $numThreads\
 --markOrigins --markTerminations --markForks

# remove the temporary file
rm "$temp_detect_file"